server:
    port: 8082

spring:
    application:
        name: @artifactId@
        version: @project.version@
    output:
        ansi:
            enabled: ALWAYS

app:
    server:
        hostname: bluelight.mx
        port: 22
        folderHome: home
        channel: sftp

springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
