spring:
    application:
        name: @artifactId@
        version: @project.version@
        baseUrl: https://63975c7a86d04c7633935b72.mockapi.io/api
        insurance:
            url: /insurance
            contract: ${spring.application.baseUrl}${spring.application.insurance.url}/contract
            policies: ${spring.application.baseUrl}${spring.application.insurance.url}/policies
    output:
        ansi:
            enabled: ALWAYS

springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
