spring:
    application:
        name: @artifactId@
        version: @project.version@
    output:
        ansi:
            enabled: ALWAYS

app:
    baseUrl: https://63975c7a86d04c7633935b72.mockapi.io/api
    insurance:
        url: /insurance
        contract: ${app.baseUrl}${app.insurance.url}/contract

springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
